<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-08-24 16:34
=======
# Generated by Django 4.1 on 2022-08-24 12:31
>>>>>>> 7a623ef6432ac2f65e5db8f8d3faf9bd78bf7378

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
